/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Administrator: typeof import('./../layouts/administrator/index.vue')['default']
    Administrator_1: typeof import('./../layouts/administrator_1/index.vue')['default']
    AntDesignIcon: typeof import('./../components/ant-design-icon/index.vue')['default']
    AsideHeaderSection: typeof import('./../layouts/aside-header-section/index.vue')['default']
    Custom: typeof import('./../components/custom/index.vue')['default']
    'IAkarIcons:fullScreen': typeof import('~icons/akar-icons/full-screen')['default']
    'IAkarIcons:normalScreen': typeof import('~icons/akar-icons/normal-screen')['default']
    Icones: typeof import('./../components/icones/index.vue')['default']
    'IFluent:settings24Regular': typeof import('~icons/fluent/settings24-regular')['default']
    'IFxemoji:crescentmoon': typeof import('~icons/fxemoji/crescentmoon')['default']
    'IFxemoji:sunrays': typeof import('~icons/fxemoji/sunrays')['default']
    'IIconoir:refresh': typeof import('~icons/iconoir/refresh')['default']
    'IIon:iosArrowRight': typeof import('~icons/ion/ios-arrow-right')['default']
    'ILineMd:menuFoldLeft': typeof import('~icons/line-md/menu-fold-left')['default']
    'ILineMd:menuUnfoldRight': typeof import('~icons/line-md/menu-unfold-right')['default']
    'IMajesticons:arrowsCollapseFullLine': typeof import('~icons/majesticons/arrows-collapse-full-line')['default']
    'IMajesticons:arrowsExpandFullLine': typeof import('~icons/majesticons/arrows-expand-full-line')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEl: typeof import('naive-ui')['NEl']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
