/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Administrator: typeof import('./../layouts/administrator/index.vue')['default']
    AsideHeaderSection: typeof import('./../layouts/aside-header-section/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
